In [1]:
import torch
from torch.utils import data

In [4]:
x = torch.randn(5, 4)
y = torch.arange(5)
dataset = data.TensorDataset(x, y)
for a in dataset:
    print(a)

(tensor([-0.5651,  0.8501, -0.4886, -0.3757]), tensor(0))
(tensor([-0.1317,  0.3896, -1.9172, -0.2408]), tensor(1))
(tensor([ 0.2475, -2.1079,  0.3290,  1.7148]), tensor(2))
(tensor([-1.0254, -1.0775,  0.7546, -0.1582]), tensor(3))
(tensor([ 0.0376, -1.5754,  0.3051, -0.6058]), tensor(4))


In [7]:
batch = data.DataLoader(dataset, batch_size=2, shuffle=True)
for value, label in batch:
    print(value)
    print(label)

tensor([[ 0.2475, -2.1079,  0.3290,  1.7148],
        [ 0.0376, -1.5754,  0.3051, -0.6058]])
tensor([2, 4])
tensor([[-0.1317,  0.3896, -1.9172, -0.2408],
        [-1.0254, -1.0775,  0.7546, -0.1582]])
tensor([1, 3])
tensor([[-0.5651,  0.8501, -0.4886, -0.3757]])
tensor([0])
